name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Try curl to get to opensource.org
      run: |
        curl -I https://opensource.org/ \
          -v \
          --http1.1 \
          -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0 Sphinx/7.2.6" \
          -H "Accept-Encoding: gzip, deflate" \
          -H "Accept: */*" \
          -H "Connection: keep-alive"

    - name: Install Requirements
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch external sources
      run: |
        bash .github/scripts/fetch_external_sources.sh
    - name: Sphinx build
      run: |
        sphinx-build -M html . build
        sphinx-build -b linkcheck . linkcheck
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/html
