name: notebook-doctest

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *' # end of every day



jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw.hsf.org/key4hep/setup.sh', '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
        PAGE: ['k4marlinwrapper/doc/starterkit/k4MarlinWrapperCLIC/Readme']
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d clicdp/cc7-lcg /bin/bash
    - name: Setup container
      run: |
        docker exec CI_container /bin/bash -c ' ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so;\
        '

    - name: CheckPage  
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\
        source ${{ matrix.SETUP }};\
        git clone --depth 1 https://github.com/key4hep/k4marlinwrapper;\
        cat .github/scripts/yamlheader.md  ${{ matrix.PAGE }}.md > ${{ matrix.PAGE }}-test.md;\
        testfilename=$(basename ${{ matrix.PAGE }}-test.md);\
        testdirname=$(dirname ${{ matrix.PAGE }}-test.md);\
        cd $testdirname;\
        jupytext $testfilename -o ${testfilename/-test.md/.ipynb} --execute;\
        '
